// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASu4KMN8r_T-DxUuNMwRpjHSGghV44y2g',
    appId: '1:429826143062:web:f37c4b50bd6f77f66a9cf7',
    messagingSenderId: '429826143062',
    projectId: 'chatmessenger-235d5',
    authDomain: 'chatmessenger-235d5.firebaseapp.com',
    storageBucket: 'chatmessenger-235d5.appspot.com',
    measurementId: 'G-LE6KGW9PY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC54XFcqUqyaWTr_riHXnd3a6o2bikNXNw',
    appId: '1:429826143062:android:cab4ebcf1fba85d46a9cf7',
    messagingSenderId: '429826143062',
    projectId: 'chatmessenger-235d5',
    storageBucket: 'chatmessenger-235d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfgNSD4NuNEMcZL2T_4iorh4364Cd0c7M',
    appId: '1:429826143062:ios:f958092f6cb1717c6a9cf7',
    messagingSenderId: '429826143062',
    projectId: 'chatmessenger-235d5',
    storageBucket: 'chatmessenger-235d5.appspot.com',
    iosBundleId: 'com.example.chatMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfgNSD4NuNEMcZL2T_4iorh4364Cd0c7M',
    appId: '1:429826143062:ios:bb084c08209433416a9cf7',
    messagingSenderId: '429826143062',
    projectId: 'chatmessenger-235d5',
    storageBucket: 'chatmessenger-235d5.appspot.com',
    iosBundleId: 'com.example.chatMessenger.RunnerTests',
  );
}
